theme: jekyll-theme-cayman
title: mowery.dev
description: Pretty much just recipes
google_analytics: UA-165281829-1
recipes:
  - cheesebread:
      name: "cheese_bread",
      tags:
        - "snack"

