# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Jeremy Mowery
email: jermowery@email.arizona.edu
description: > # this means to ignore newlines until "baseurl:"
  Projects and professional details.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://jermowery.github.io" # the base hostname & protocol for your site
github_username:  jermowery
linkedin_username: jeremy-mowery-7084b256

# Build settings
markdown: kramdown
