theme: jekyll-theme-cayman
title: mowery.dev
description: Pretty much just recipes
google_analytics: UA-165281829-1
recipes: 
  - 
    name: cheese bread
    file_name: cheese_bread.html
    tags: 
      - snack
  - 
    name: chickpea orzo soup
    file_name: chickpea_orzo_soup.html
    tags: 
      - soup
      - dinner
  - 
    name: cinnamon rolls
    file_name: cinnamon_rolls.html
    tags: 
      - dessert
  - 
    name: fondue
    file_name: fondue.html
    tags: 
      - dinner
  - 
    name: greek chicken
    file_name: greek_chicken.html
    tags: 
      - lunch
      - dinner
  - 
    name: greek salad
    file_name: greek_salad.html
    tags: 
      - unfinished
      - lunch
      - dinner
  - 
    name: smashed potatoes
    file_name: smashed_potatoes.html
    tags: 
      - lunch
      - dinner
      - unfinished
  - 
    name: tzatziki
    file_name: tzatziki.html
    tags: 
      - lunch
      - dinner
      - sauce
      - unfinished
  - 
    name: waffles
    file_name: waffles.html
    tags: 
      - breakfast
  -
    name: carrot cake
    file_name: carrot_cake.html
    tags:
      - dessert
  -
    name: cobbler
    file_name: cobbler.html
    tags:
      - dessert
  -
    name: the one true rice
    file_name: rice.html
    tags:
      - dinner
      - lunch


