baseURL = 'https://mowery.dev'
languageCode = 'en-us'
title = 'mowery.dev'
theme = ['hugo-notice', 'ananke']
enableEmoji = true
enableGitInfo = true
googleAnalytics = 'G-TYW7RZVTRH'
Paginate = 1000
defaultContentLanguage = 'en'
enableRobotsTXT = true

[params]
    show_reading_time = true
    disable_share = false
    background_color_class = "bg-purple"
    private = false
    description = "A delicious recipe"

[languages]
  [languages.en]
    weight = 1
  [languages.de]
    weight = 2
  [languages.pt-br]
    weight = 2

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[markup.goldmark.renderer]
    unsafe= true

[taxonomies]
  category = 'categories'
  tag = 'tags'
  author = "author"