baseURL = 'https://mowery.dev'
languageCode = 'en-us'
title = 'mowery.dev'
theme = ['hugo-notice', 'ananke']
enableEmoji = true
enableGitInfo = true
googleAnalytics = 'UA-165281829-1'
Paginate = 1000

[params]
    show_reading_time = true
    disable_share = false
    background_color_class = "bg-purple"
    private = false
    description = "A delicious recipe"

[markup.goldmark.renderer]
    unsafe= true